### PR TITLE
Option 1: Add index to pairing labels

### LINKED ISSUE #201: [PE-D][Tester D] pair command outputs incorrect message when used after find command
**Description**
When pairing a person after using the find command, the success message displays incorrectly.

**Steps to reproduce**
1. `find KEYWORD`
2. `pair INDEX 1ST_PARTNER_INDEX`

**Expected Behaviour**
The success message should correctly show the names of the paired contacts: `Paired: Irfan Ibrahim to {rew}`

**Actual Behaviour**
The output message incorrectly displays: `Paired: Irfan Ibrahim to {Irfan Ibrahim}`

Image

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### LINKED ISSUE #225: [PE-D][Tester B] Regarding tags to show pairings
Two persons having the same name may not imply they are duplicates. However there can be visibility issues that arise. In the example below, which student is paired to which volunteer?
A solution would be to use something more distinct for the tag.

Image

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### PR DESCRIPTION
**Pull request by chleheng**
Fix #225. Fix #201 
image

### CODE REVIEW

File: src/main/java/seedu/address/ui/PersonCard.java [hunk 1]
```diff
@@ -54,10 +53,11 @@ public class PersonCard extends UiPart<Region> {
     /**
      * Creates a {@code PersonCode} with the given {@code Person} and index to display.
      */
-    public PersonCard(ReadOnlyAddressBook addressBook, Person person, int displayedIndex) {
+    public PersonCard(ReadOnlyAddressBook addressBook, ObservableList<String> pairings, Person person,
+                      int displayedIndex) {
```
Comment (recursive-rc) [inline src/main/java/seedu/address/ui/PersonCard.java]: According to the [course Java standard](https://se-education.org/guides/conventions/java/intermediate.html#comments),

> `@param`s can be omitted if _all_ parameters of a method have self-explanatory names, or they are already explained in the main part of the comment i.e., if none of the `@param`s add any value. This means the comment will have `@param` for all its parameters, or none.

Is the name of the`pairings` parameter "self-explanatory"? For instance, a reader seeing it may have a few questions:

* Should it include all the pairings in the address book, or only those in the filtered list, or only those the person is paired to?
* What format should the string have? Is it just the person's name? The string representation when calling `toString()`?

Could this be explained in the Javadoc header comment for this method? Do note that header comments seem to be counted in the functional code count, so I would consider this lower priority if you have limited LoC you can change.

File: src/main/java/seedu/address/ui/PersonCard.java [hunk 2]
```diff
@@ -76,7 +76,7 @@ public PersonCard(ReadOnlyAddressBook addressBook, Person person, int displayedI
     private void renderPairings() {
         pairings.getChildren().clear();
         observablePairings.stream()
-                .sorted(Comparator.comparing(pairing -> pairing.getName().toString()))
-                .forEach(pairing -> pairings.getChildren().add(new Label(pairing.getName().toString())));
+                .sorted(Comparator.comparing(pairing -> pairing.split("\\.")[0]))
```
Comment (recursive-rc) [inline src/main/java/seedu/address/ui/PersonCard.java]: Does `"\\.."` count as a [magic literal](https://nus-cs2103-ay2526s1.github.io/website/se-book-adapted/chapters/codeQuality.html#avoid-magic-numbers)?

Comment (c-j-lh) [reply src/main/java/seedu/address/ui/PersonCard.java]: addressed
