### PR TITLE
Pair by id

### LINKED ISSUE #82: Only allow pairing students to volunteers and vice versa

### LINKED ISSUE #96: Bugs in `pair` and `unpair` commands
There are the following bugs in the `pair` and `unpair` commands:

1. When user enters a `unpair` command when the pair does not already exist (for example, entering `unpair 1 2` when the persons corresponding to indexes 1 and 2 were not previously paired), `AssertionError` and `InvocationTargetException` are thrown without any GUI change.
2. When user enters `pair` command for an already existing pair (for example, entering `pair 1 2` or `pair 1 2 3` when there is already a pair between the first and second persons), `AssertionError` and `InvocationTargetException` are thrown without any GUI change.
3. When all the indexes in a `pair` or `unpair` command are the same (such as `pair 1 1` or `unpair 2 2 2 2`), the error message shown to user is "At least one index to pair/unpair is required." I think this is somewhat misleading.
5. When duplicate indexes are typed in any `pair` or `unpair` command and there are at least two distinct indexes (such as `pair 5 6 5` or, after pairing persons 5 & 6, `unpair 6 5 5`), no error or warning is shown to user in GUI.

### LINKED ISSUE #104: Pair by id

### LINKED ISSUE #119: No message logging for savefiles' invalid lines being silently ignored
No message logging for savefiles' invalid lines being silently ignored
e.g., duplicate pairings, self-pairings

### LINKED ISSUE #123: Pairing needs to use ids instead of Person references now that Person is immutable once again

### PR DESCRIPTION
**Pull request by chleheng**
Fixes #104 
Fix #82
Fix #96

('alpha-bug' issues:)
Fix #119 
Fix #123 

missing test coverage - do we really need it?

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/PairCommand.java [hunk 1]
```diff
@@ -51,41 +54,69 @@ public CommandResult execute(Model model) throws CommandException {
...
         if (index.getZeroBased() >= lastShownList.size()) {
-            throw new CommandException(Messages.MESSAGE_INVALID_PERSON_DISPLAYED_INDEX);
+            throw new CommandException(Messages.MESSAGE_INVALID_FIRST_PERSON_DISPLAYED_INDEX);
         }
 
         Person person = lastShownList.get(index.getZeroBased());
 
         Set<Person> personsToPair = new HashSet<>();
+        Set<Index> invalidIndices = new HashSet<>();
+        Set<Pair<Index, Person>> personsAlreadyPaired = new HashSet<>();
```
Comment (recursive-rc) [inline src/main/java/seedu/address/logic/commands/PairCommand.java]: Question :question:: Should finding incorrect indexes entered by user be the responsibility of the Command class or the Parser class?

**Review by bentandj — APPROVED** [review]
Good work on fixing the bugs. As of now I couldn't find any obvious ones.

File: src/main/java/seedu/address/storage/JsonSerializableAddressBook.java [hunk 2]
```diff
@@ -26,98 +26,89 @@ class JsonSerializableAddressBook {
...
-
-                try {
-                    owner.addPerson(target);
-                } catch (IllegalValueException ive) {
-                    // duplicate pairings in savefile, silently ignore
+                int x = Math.min(a, b);
+                int y = Math.max(a, b);
+                long key = (((long) x) << 32) ^ (y & 0xffffffffL);
+                if (seen.add(key)) {
+                    if (!list.get(x).getType().equals(list.get(y).getType())) {
```
Comment (mihirshah2005) [inline src/main/java/seedu/address/storage/JsonSerializableAddressBook.java]: This might be flagged as arrowhead style of code as it's the 4th level of a for loop. Perhaps we can extract these inner loops into a new method? 

A lot of the conditional statements are for logging so shouldn't be an issue but I'm afraid someone might flag it out if they view this part in the PE

Comment (c-j-lh) [reply src/main/java/seedu/address/storage/JsonSerializableAddressBook.java]: goot catch.
i've fixed typo and refactored to

if (!seen.add(key)) {
                    Logger.getGlobal().warning("Ignoring and not loading duplicate pairing: "
                            + list.get(x) + " and " + list.get(y));
                    continue;
                }

                if (list.get(x).getType().equals(list.get(y).getType())) {
                    Logger.getGlobal().warning("Ignoring and not loading pairing between two persons"
                            + " of the same type: " + list.get(x) + " and " + list.get(y));
                    continue;
                }
                pairings.add(new JsonPairing(x, y));
