### PR TITLE
Fix optional details

### LINKED ISSUE #77: Improve implementation of optional contact details
As mentioned in #61 , contact details were made optional with a quick and dirty fix. In the long run, it would be better to improve the implementation now so that less issues crop up later.

**Sub-Issues**
1. Default values are hardcoded.
2. Unused imports are commented out instead of simply deleted.
3. Manual if-else checks were added to AddCommandParser.java to set null fields to default values is verbose, prone to error and not scalable.
4. The constructor for Person.java still requires all fields even though only one is required, which makes it difficult to use.
5. Due to a recent update (#67), Person.java internal fields are made not final and setters are added, breaking immutability. While it's okay currently, it could cause unexpected bugs as development progresses.
6. The changes (#67) in EditCommand.java and the code in the execute function is not concise.

Planned implementation: 

(Point 4) According to Chapter 2 in _Bloch (2018) Effective Java_ that Ranen sent, a traditional approach to allowing creation of an object with less fields is the telescoping constructor pattern, in which constructors with varying combinations of parameters are added. However, this is difficult to read and manage. The JavaBeans method (which the new setters currently allow) makes it very flexible to create objects with optional parameters, but is more prone to inconsistency and breaks immutability. A middle ground, however, is the Builder pattern - it allows for mutability yet flexibility. This is the main component that will be implemented.

(Point 1) Public static final constants in Person.java can reduce the hardcoding of default values.

(Point 2) Trivial fix.

(Point 3) By making use of the new Builder pattern, these if-else checks can be replaced by more concise and readable code.

(Point 5 and Point 6) By setting Person.java internal fields back to final and ensuring immutability, while using the new Builder pattern, the code in EditCommand.java can be made more concise as well.

### PR DESCRIPTION
**Pull request by bentandj**
Fixes #77 

I didn't have time to fully refactor everything - however, I did manage to implement the Builder pattern. While there isn't really a functional change in the behavior of the program,

1. I reverted Person.java back to the original relatively immutable code (still not entirely immutable as Set and List are still used). This means I reverted the parameters back to final. The setters return a new instance of Person.
2. Minor refactoring.

To-do:
1. I feel that there's some potential to make the code more extendable and concise with the use of generics, since there is still a lot of 'repeated' code, e.g. across the Person, Student and Volunteer classes.
2. With more refactoring, the usage of less necessary constructors like `public Person(Name name, Phone phone, Email email, Address address, Set<Tag> tags, List<Person> pairedPersons)` can be removed.

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Person.java [hunk 1]
```diff
@@ -25,57 +25,189 @@ public class Person {
...
+    private final Email email;
 
     // Data fields
-    private Address address;
-    private Set<Tag> tags = new HashSet<>();
-    private final ObservableList<Person> pairedPersons = FXCollections.observableArrayList();
-    private final ObservableList<Person> unmodifiablePairedPersons =
-        FXCollections.unmodifiableObservableList(pairedPersons);
-    private final List<Person> unmodifiablePairingsView = Collections.unmodifiableList(pairedPersons);
+    private final Address address;
```
Comment (mihirshah2005) [inline src/main/java/seedu/address/model/person/Person.java]: This looks like a good change for the longer run as making the fields final is more defensive, but will it break our existing pair command when using the edit command?

**Review by mihirshah2005 — APPROVED** [review]
LGTM, just a few nits that can be addressed.

File: src/main/java/seedu/address/model/person/Student.java [hunk 2]
```diff
@@ -12,17 +12,34 @@
...
+        public Student build() {
+            return new Student(this);
+        }
+    }
+
+    private Student(StudentBuild builder) {
+        super(builder);
+    }
+
+    public Student(Name name, Phone phone, Email email, Address address, Set<Tag> tags, List<Person> pairedPersons) {
```
[the remark this answers is not in the document]
Comment (bentandj) [reply src/main/java/seedu/address/model/person/Student.java]: Added back

File: src/main/java/seedu/address/model/person/Person.java [hunk 3]
```diff
@@ -31,51 +31,167 @@ public class Person {
...
+        private Email email = new Email("default@email");
+        private Address address = new Address("Default Address");
+        private Set<Tag> tags = new HashSet<>();
+        private ObservableList<Person> pairedPersons = FXCollections.observableArrayList();
+
+        /**
+         * Constructor for PersonBuild.
+         */
+        public PersonBuild(Name name) {
+            requireAllNonNull(name);
```
Comment (c-j-lh) [inline src/main/java/seedu/address/model/person/Person.java]: nit: could use `import static java.util.Objects.requireNonNull` instead since there's only 1

File: src/main/java/seedu/address/model/person/Person.java [hunk 4]
```diff
@@ -96,25 +212,45 @@ public List<Person> getPairedPersons() {
...
     }
 
-    public void setTags(Set<Tag> tags) {
+    /**
+     * Returns a new Person object with the specified tags.
+     */
+    public Person setTags(Set<Tag> tags) {
         this.tags = tags;
+        return this;
     }
```
Comment (c-j-lh) [inline src/main/java/seedu/address/model/person/Person.java]: Interesting, I wonder how this will work out in future iterations. Let's discuss next meeting

File: src/main/java/seedu/address/model/person/Person.java [hunk 5]
```diff
@@ -31,51 +31,167 @@ public class Person {
...
-        this.name = name;
-        this.phone = phone;
-        this.email = email;
-        this.address = address;
-        this.tags.addAll(tags);
-        this.pairedPersons.setAll(pairedPersons);
-        FXCollections.sort(this.pairedPersons, Comparator.comparing(p -> p.getName().toString()));
+        PersonBuild<?> builder = new PersonBuild<>(name).phone(phone).email(email).address(address)
+                .tags(tags).pairedPersons(pairedPersons);
+        requireAllNonNull(builder.name, builder.phone, builder.email, builder.address,
```
[the remark this answers is not in the document]
Comment (bentandj) [reply src/main/java/seedu/address/model/person/Person.java]: It's a bit like an assert statement, it's there to break if any value is somehow null, but it can also be removed
