### PR TITLE
Fix parsing in addstu/addvol

### LINKED ISSUE #100: Fix parsing in Name and Phone fields of addstu/addvol
Allow country code, spaces and dashes for phone number.
Allow unicode with restrictions for name.

### PR DESCRIPTION
**Pull request by mihirshah2005**
Fixes #100

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Name.java
Comment (bentandj) [inline src/main/java/seedu/address/model/person/Name.java]: Well written and comprehensive!

File: src/main/java/seedu/address/model/person/Phone.java [hunk 1]
```diff
@@ -10,9 +10,15 @@
...
+    /**
+     * Phone numbers may:
+     *   Optionally start with a '+' (for country code),
+     *   Contain digits, spaces, and dashes,
+     *   Contain at least 3 digits in total.
+     */
     public static final String MESSAGE_CONSTRAINTS =
-            "Phone numbers should only contain numbers, and it should be at least 3 digits long";
-    public static final String VALIDATION_REGEX = "\\d{3,}";
+            "Phone numbers must have at least 3 digits, may start with '+', and may include spaces or dashes.";
```
Comment (bentandj) [inline src/main/java/seedu/address/model/person/Phone.java]: Another small thing to consider is whether to allow parentheses and dots in phone numbers, since some other countries use those. But it's also okay if this is not added as E.164 only uses + and digits anyway.

**Review by bentandj — APPROVED** [review]
I feel the added parsing is well-written and functional. I also like the test cases and assertions that you added. LGTM, just see my comment on the call to canonicalize in the Phone constructor.

File: src/main/java/seedu/address/model/person/Name.java [hunk 2]
```diff
@@ -38,6 +47,71 @@ public static boolean isValidName(String test) {
...
+     */
+
+    public static String normalizeForIdentity(String s) {
+
+        if (s == null) {
+            throw new NullPointerException(MESSAGE_CONSTRAINTS);
+        }
+
+        // 1) Unicode normalize and case-fold
+        String n = Normalizer.normalize(s, Normalizer.Form.NFKC).toLowerCase();
```
[the remark this answers is not in the document]
Comment (mihirshah2005) [reply src/main/java/seedu/address/model/person/Name.java]: Fixed thanks

**Review by bentandj — APPROVED** [review]
LGTM

**Review by c-j-lh — APPROVED** [review]
1. Mixing LTR and RTL and Top-to-Bottom scripts work
image
image


2. I put a weird space character. It was still detected by `\s`.

This probably isn't a bug. At most the user will be confused* since this space character is invisible? Unless you feel like deleting/replacing sus characters with "" in AddressBookParser or something.

*if they hypothetically nonmaliciouslycopied a name with this weird space from somewhere

image

Remember to mention in the user guide that "p/", "n/" etc. that conflict with existing syntax are not valid in names. E.g., not `edit 1 n/Adam p/o John`. I wouldn't've been brave enough to allow all Unicode for PE, gotta respect the effort.
