### PR TITLE
Immutable person

### LINKED ISSUE #88: Make Person class immutable
In this issue, the following primary concerns will be addressed:
 
1. As discussed in the previous meeting, we've agreed to make the Person class immutable. This means making its fields final, and creating a new Person everytime it's modified.
2. It was also mentioned that there was existing PersonBuilder, StudentBuilder, VolunteerBuilder classes under the test folder. These will be deleted.

After further code inspection, the following secondary concerns will be addressed:

1. There is much overlap between the code of the EditPersonDescriptor class used in EditCommand, and the new PersonBuilder class. As such, the PersonBuilder class will replace the EditPersonDescriptor class to make future changes easier (no need to change in two places for a single update).
2. Similarly, there is much overlap between the EditPersonDescriptorBuilder class under the testutil folder. Again, the new PersonBuilder class will replace the EditPersonDescriptorBuilder class.
3. Some of the tests are not updated, while others are buggy. The code for these will be refactored and resolved, with the exception of 2 tests under LogicManagerTest. i.e. the number of test cases passed will be 322/324.

### PR DESCRIPTION
**Pull request by bentandj**
Fixes #88 .

In terms of LOC, this is a big change, however a lot of it is just refactoring. I've summarized the main changes below:

1. The Person class is now immutable. It's fields are final, and a new Person is created everytime it's modified.
2. The existing PersonBuilder, StudentBuilder, VolunteerBuilder classes under the test folder have been deleted.
3. The EditPersonDescriptor class used in EditCommand has been replaced by the new PersonBuilder class. This also means the EditPersonDescriptorBuilder class under the testutil folder has been updated accordingly.
4. Tests that were buggy or not updated have been refactored and updated. I've made minor changes in miscellaneous classes to pass these tests. All tests currently pass.

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Person.java [hunk 1]
```diff
@@ -24,78 +26,207 @@ public class Person {
...
-            this.name = name;
+        public PersonBuilder name(String name) {
+            return this.name(new Name(name));
+        }
+
+        /**
+         * Setter for the name parameter but only if this.name does not already exist.
+         */
+        public PersonBuilder nameIfNotPresent(Name name) {
+            if (this.name == null && name != null) {
```
Comment (recursive-rc) [inline src/main/java/seedu/address/model/person/Person.java]: Nit: Is the `name` parameter (not `this.name`) ever supposed to take the value of `null`? I tried tracing code for `edit` command with the debugger and I don't think this parameter ever takes the value of `null`. Should we throw a `NullPointerException` if it is `null`?

```suggestion
            requireNonNull(name);
            if (this.name == null) {
```

Same for other `xyzIsNotPresent` methods.

File: src/main/java/seedu/address/model/person/Person.java [hunk 2]
```diff
@@ -104,71 +235,122 @@ public PersonBuild<T> tags(Set<Tag> tags) {
...
-        this.email = builder.email;
-        this.address = builder.address;
-        this.tags = builder.tags;
-        this.pairedPersons = builder.pairedPersons;
+        this.phone = builder.phone != null ? builder.phone : DEFAULT_PHONE;
+        this.email = builder.email != null ? builder.email : DEFAULT_EMAIL;
+        this.address = builder.address != null ? builder.address : DEFAULT_ADDRESS;
+        this.tags = builder.tags != null ? builder.tags : new HashSet<>();
+        this.pairedPersons = builder.pairedPersons != null
+                ? builder.pairedPersons : FXCollections.observableArrayList();
```
Comment (recursive-rc) [inline src/main/java/seedu/address/model/person/Person.java]: Very minor nit: Would it be clearer to use `Collections.emptySet()` and `FXCollections.emptyObservableList()` to make the intended meaning of the code clearer?

```suggestion
        this.tags = builder.tags != null ? builder.tags : Collections.emptySet();
        this.pairedPersons = builder.pairedPersons != null
                ? builder.pairedPersons : FXCollections.emptyObservableList();
```

File: src/main/java/seedu/address/model/person/Person.java [hunk 3]
```diff
@@ -355,10 +496,10 @@ public boolean isSamePerson(Person otherPerson) {
...
 
         // identify real contacts
-        boolean thisHasRealPhone = !thisPhone.equals(DEFAULT_PHONE);
-        boolean otherHasRealPhone = !otherPhone.equals(DEFAULT_PHONE);
-        boolean thisHasRealEmail = !thisEmail.equals(DEFAULT_EMAIL);
-        boolean otherHasRealEmail = !otherEmail.equals(DEFAULT_EMAIL);
+        boolean thisHasRealPhone = !thisPhone.equals(DEFAULT_PHONE.value);
+        boolean otherHasRealPhone = !otherPhone.equals(DEFAULT_PHONE.value);
+        boolean thisHasRealEmail = !thisEmail.equals(DEFAULT_EMAIL.value);
+        boolean otherHasRealEmail = !otherEmail.equals(DEFAULT_EMAIL.value);
```
Comment (recursive-rc) [inline src/main/java/seedu/address/model/person/Person.java]: Nit: Would it be better to compare the respective `Phone`, `Email`, etc. objects using their `equals()` methods rather than directly accessing their `value` field? I think this would help reduce [coupling](https://nus-cs2103-ay2526s1.github.io/website/se-book-adapted/chapters/designFundamentals.html#what-2) `Person` has with `Phone`, `Email`, etc. For example, if someone changes the `phone` class to include a new field for country code, they would need to change this `isSamePerson` method implementation too.

File: src/main/java/seedu/address/model/util/SampleDataUtil.java
Comment (recursive-rc) [inline src/main/java/seedu/address/model/util/SampleDataUtil.java]: Important: could you ensure all sample persons are either a `Student` or a `Volunteer`? If not, they will not be shown in GUI due to changes in #80 (see https://github.com/AY2526S1-CS2103T-F10-1/tp/pull/80#issuecomment-3432518690 for more info).

Sorry, I realize the changes I asked Mihir to make to #80 will cause merge conflicts with these changes here. I didn't see this PR before reviewing Mihir's.

File: src/main/java/seedu/address/model/person/Person.java [hunk 4]
```diff
@@ -24,78 +26,207 @@ public class Person {
...
     private final ObservableList<Person> unmodifiablePairedPersons;
     private final List<Person> unmodifiablePairingsView;
 
+    private final PersonBuilder personBuilder;
+
     /**
      * The Builder for the Person class.
      */
-    public static class PersonBuild<T extends PersonBuild<T>> {
+    public static class PersonBuilder extends Builder<PersonBuilder> {
```
Comment (recursive-rc) [inline src/main/java/seedu/address/model/person/Person.java]: Should this class be abstract? (Can change after this milestone, no need change before merging this PR.)

File: src/main/java/seedu/address/model/util/SampleDataUtil.java
Comment (recursive-rc) [reply src/main/java/seedu/address/model/util/SampleDataUtil.java]: Fixed in commit [5097e64](https://github.com/AY2526S1-CS2103T-F10-1/tp/pull/89/commits/5097e64be3b909b9dbcdaafec9d0946b577dc3fe)

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 5]
```diff
@@ -76,7 +76,7 @@ public CommandResult execute(Model model) throws CommandException {
 
         model.setPerson(personToEdit, editedPerson);
         model.updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS);
-        if (editPersonDescriptor.getName().isPresent()) { // if name has been edited
+        if (editedPerson.getName().equals(personToEdit.getName())) { // if name has been edited
```
Comment (recursive-rc) [inline src/main/java/seedu/address/logic/commands/EditCommand.java]: ♻️ Refactor proposed: Could this be a separate line of code, in the spirit of [making code self-explanatory](https://nus-cs2103-ay2526s1.github.io/website/se-book-adapted/chapters/codeQuality.html#introduction-6)?

```suggestion
        boolean hasNameBeenEdited = editedPerson.getName().equals(personToEdit.getName());
        if (hasNameBeenEdited) {
```

File: src/main/java/seedu/address/model/person/Person.java [hunk 6]
```diff
@@ -24,78 +26,207 @@ public class Person {
...
+
+        /**
+         * Copy constructor.
+         */
+        public PersonBuilder(PersonBuilder toCopy) {
+            this.name = toCopy.name;
+            this.phone = toCopy.phone;
+            this.email = toCopy.email;
+            this.address = toCopy.address;
+            this.tags = toCopy.tags;
```
[the remark this answers is not in the document]
Comment (bentandj) [reply src/main/java/seedu/address/model/person/Person.java]: I think this will work better - I'll change this in the next iteration.

File: src/test/java/seedu/address/testutil/TypicalPersons.java [hunk 7]
```diff
@@ -120,4 +179,20 @@ public static List<Person> getSelfPairingTypicalPersons() {
...
+                new Person.PersonBuilder(ALICE).build(),
+                new Person.PersonBuilder(BOB).build(),
+                new Person.PersonBuilder(CARL).build(),
+                new Person.PersonBuilder(CARL).build(),
+                new Person.PersonBuilder(DANIEL).build(),
+                new Person.PersonBuilder(ELLE).build(),
+                new Person.PersonBuilder(FIONA).build(),
+                new Person.PersonBuilder(GEORGE).build()
+        );
+    }
```
Comment (recursive-rc) [inline src/test/java/seedu/address/testutil/TypicalPersons.java]: ♻️ Refactor proposed (low priority): This is dead code and was removed earlier (see https://github.com/AY2526S1-CS2103T-F10-1/tp/pull/67#discussion_r2433157118). I'm not sure how this got added back. Could this be removed?

File: src/main/java/seedu/address/model/person/Person.java [hunk 8]
```diff
@@ -24,78 +26,207 @@ public class Person {
...
+            }
+            return this;
+        }
 
         /**
-         * Constructor for PersonBuild.
+         * Setter for the name parameter but with String argument.
          */
-        public PersonBuild(Name name) {
-            requireAllNonNull(name);
```
[the remark this answers is not in the document]
Comment (bentandj) [reply src/main/java/seedu/address/model/person/Person.java]: Hmm I think it's currently okay because there is a non-null check when PersonBuilder.build() is called. However if you still feel it's necessary I'll change it.

File: src/main/java/seedu/address/model/person/Person.java [hunk 9]
```diff
@@ -24,78 +26,207 @@ public class Person {
...
-            this.name = name;
+        public PersonBuilder name(String name) {
+            return this.name(new Name(name));
+        }
+
+        /**
+         * Setter for the name parameter but only if this.name does not already exist.
```
[the remark this answers is not in the document]
Comment (bentandj) [reply src/main/java/seedu/address/model/person/Person.java]: Good point, will change in the next iteration.

File: src/main/java/seedu/address/model/person/Person.java [hunk 10]
```diff
@@ -24,78 +26,207 @@ public class Person {
...
-        private Set<Tag> tags = new HashSet<>();
-        private ObservableList<Person> pairedPersons = FXCollections.observableArrayList();
+        private Phone phone;
+        private Email email;
+        private Address address;
+        private Set<Tag> tags;
+        private ObservableList<Person> pairedPersons;
+
+        /**
+         * Constructor for PersonBuilder.
```
[the remark this answers is not in the document]
Comment (bentandj) [reply src/main/java/seedu/address/model/person/Person.java]: Very observant, will change in the next iteration.

File: src/test/java/seedu/address/testutil/TypicalPersons.java (hunk 7 above)
Comment (bentandj) [reply src/test/java/seedu/address/testutil/TypicalPersons.java]: Will probably remove in the following iterations.
